# Generated by Django 2.1.2 on 2018-11-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docFile', models.FileField(default='dummy.txt', upload_to='documents/')),
            ],
        ),
    ]
